project:
  type: website
  output-dir: docs
website:
  title: "Shashank's Blog"
  navbar:
    right:
      - about.qmd
      - icon: website
        href: https://shashankshekhar.me
      - icon: github
        href: https://github.com/shashank2806
      - icon: twitter
        href: https://twitter.com/shekhar28june
format:
  html:
    theme: cosmo
    css: styles.css



